---
name: push bi-daily
on:
  schedule:
    - cron: '1 8,17 * * *'
      on:
        pull:
          push:
            branches:
              - main
          pull_request:
            branches:
              - main
